"""first

Revision ID: e601117d846b
Revises: 
Create Date: 2025-11-04 16:03:15.604671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e601117d846b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.CheckConstraint("name != ''", name='chk_ingredients_non_empty_name'),
    sa.CheckConstraint("unit != ''", name='chk_ingredients_non_empty_unit'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_ingredients_name', 'ingredients', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('other_data', sa.String(), nullable=True),
    sa.Column('goals', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height IS NULL OR height > 0', name='chk_user_settings_positive_height'),
    sa.CheckConstraint('weight IS NULL OR weight > 0', name='chk_user_settings_positive_weight'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    op.create_table('weekly_diets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date < end_date', name='chk_weekly_diets_date_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weekly_diets_dates', 'weekly_diets', ['user_id', 'start_date', 'end_date'], unique=False)
    op.create_index('idx_weekly_diets_user_created', 'weekly_diets', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_weekly_diets_user_id', 'weekly_diets', ['user_id'], unique=False)
    op.create_table('grocery_lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('weekly_diet_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_diet_id'], ['weekly_diets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grocery_lists_weekly_diet_id', 'grocery_lists', ['weekly_diet_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('weekly_diet_id', sa.String(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('recipe', sa.String(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.CheckConstraint('calories >= 0', name='chk_meals_positive_calories'),
    sa.CheckConstraint('day >= 0 AND day <= 6', name='chk_meals_valid_day'),
    sa.ForeignKeyConstraint(['weekly_diet_id'], ['weekly_diets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meals_weekly_diet_day', 'meals', ['weekly_diet_id', 'day'], unique=False)
    op.create_index('idx_meals_weekly_diet_id', 'meals', ['weekly_diet_id'], unique=False)
    op.create_index('idx_meals_weekly_diet_type', 'meals', ['weekly_diet_id', 'meal_type'], unique=False)
    op.create_table('grocery_list_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grocery_list_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_grocery_list_items_positive_quantity'),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grocery_list_items_grocery_ingredient', 'grocery_list_items', ['grocery_list_id', 'ingredient_id'], unique=False)
    op.create_index('idx_grocery_list_items_grocery_list_id', 'grocery_list_items', ['grocery_list_id'], unique=False)
    op.create_index('idx_grocery_list_items_ingredient_id', 'grocery_list_items', ['ingredient_id'], unique=False)
    op.create_table('meal_ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meal_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_meal_ingredients_positive_quantity'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meal_ingredients_ingredient_id', 'meal_ingredients', ['ingredient_id'], unique=False)
    op.create_index('idx_meal_ingredients_meal_id', 'meal_ingredients', ['meal_id'], unique=False)
    op.create_index('idx_meal_ingredients_meal_ingredient', 'meal_ingredients', ['meal_id', 'ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_meal_ingredients_meal_ingredient', table_name='meal_ingredients')
    op.drop_index('idx_meal_ingredients_meal_id', table_name='meal_ingredients')
    op.drop_index('idx_meal_ingredients_ingredient_id', table_name='meal_ingredients')
    op.drop_table('meal_ingredients')
    op.drop_index('idx_grocery_list_items_ingredient_id', table_name='grocery_list_items')
    op.drop_index('idx_grocery_list_items_grocery_list_id', table_name='grocery_list_items')
    op.drop_index('idx_grocery_list_items_grocery_ingredient', table_name='grocery_list_items')
    op.drop_table('grocery_list_items')
    op.drop_index('idx_meals_weekly_diet_type', table_name='meals')
    op.drop_index('idx_meals_weekly_diet_id', table_name='meals')
    op.drop_index('idx_meals_weekly_diet_day', table_name='meals')
    op.drop_table('meals')
    op.drop_index('idx_grocery_lists_weekly_diet_id', table_name='grocery_lists')
    op.drop_table('grocery_lists')
    op.drop_index('idx_weekly_diets_user_id', table_name='weekly_diets')
    op.drop_index('idx_weekly_diets_user_created', table_name='weekly_diets')
    op.drop_index('idx_weekly_diets_dates', table_name='weekly_diets')
    op.drop_table('weekly_diets')
    op.drop_index('idx_user_settings_user_id', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_ingredients_name', table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
